postreise/plot/colors.py
postreise/plot/multi/constants.py
postreise/plot/plot_shadowprice_map.py
postreise/plot/tests/test_plot_shadowprice_map.py

Improve `plot_shadowprice_map` module. Changes are mostly related to docstring
Ran associated notebook
* `plot_shadowprice_map`:
+ format docstring
+ check type of parameters and raise errors
+ rename variable `hour` to `date`
+ change query for index in data frame and name of column
* `shadowprice_map_demo`: 
+ import `show` from `bokeh.io` and encapsulate the call to `plot_shadowprice`
+ import `pandas` and use `pd.Timestamp` to pass the timestamp of the hour to plot to `plot_shadowprice`
`shadowprice_map_demo` notebook
10 min

Improve shadow price plotting module

---

postreise/analyze/transmission/congestion.py
postreise/analyze/transmission/tests/test_congestion_surplus.py

- Remove redundant function which gets bus demand. See performance comparison in https://github.com/Breakthrough-Energy/PowerSimData/pull/388.
- Refactor the congestion surplus tests from `unittest` to `pytest` to get to `monkeypatch` functionality (& general succinctness)
- Refactor test of congestion surplus calculation to monkeypatch around the `InputData.get_data` method which relies on profile CSVs. (see https://docs.pytest.org/en/stable/monkeypatch.html)
10 minutes, mostly for understanding the test changes.

refactor: remove redundant map_demand_to_buses

---

postreise/analyze/generation/binding.py
postreise/analyze/generation/tests/test_binding.py
postreise/analyze/tests/test_demand.py
postreise/analyze/time.py
postreise/plot/analyze_pg.py
postreise/plot/plot_curtailment_ts.py
postreise/plot/plot_generation_ts_stack.py
tox.ini

We can take advantage of isort's built in "profile" for black compatibility. This includes a line length option which we were msising, along with a couple others I'm not sure about. [Source](https://github.com/PyCQA/isort/blob/develop/isort/profiles.py) from their repo is easy to read.
Added isort section in tox.ini
Ran `tox -e format` locally, and ci passes.
5 min

ci: use built in black profile for isort

---

setup.py

Fix out of date setup.py
1 min

Update org info

---

postreise/analyze/generation/curtailment.py

```python
>>> from powersimdata.scenario.scenario import Scenario
>>> from postreise.analyze.generation.curtailment import calculate_curtailment_time_series_by_areas_and_resources
>>> calculate_curtailment_time_series_by_areas_and_resources(Scenario(549))
```
Broken before, works now.
10 seconds.

fix: typo in curtailment summarization

---

postreise/analyze/check.py
postreise/analyze/demand.py
postreise/analyze/generation/curtailment.py
postreise/analyze/generation/emissions.py
postreise/analyze/generation/summarize.py
postreise/analyze/generation/tests/test_capacity_value.py
postreise/analyze/generation/tests/test_curtailment.py
postreise/analyze/generation/tests/test_emissions.py
postreise/analyze/generation/tests/test_summarize.py
postreise/analyze/helpers.py
postreise/analyze/tests/test_demand.py
postreise/analyze/tests/test_helpers.py
postreise/plot/demo/emissions_map_demo.ipynb
postreise/plot/plot_bar_generation_vs_capacity.py
postreise/plot/plot_curtailment_ts.py
postreise/plot/plot_energy_carbon_stack.py
postreise/plot/plot_generation_ts_stack.py
postreise/plot/plot_interconnection_map.py
postreise/plot/plot_pie_generation_vs_capacity.py

Abstract grid model
Use the new `grid_model` entry in the scenario information to access the constants of the grid model.
All tests pass when the `model` branch in **PowerSimData** is checked out
everywhere.
20min

Abstract grid model

---

postreise/plot/demo/loadzone_centers.csv
postreise/plot/demo/powerflow_snapshot_demo.py
postreise/plot/plot_powerflow_snapshot.py

Add plot of powerflow snapshot to the codebase.
`plot_powerflow_snapshot` is the main function, `aggregate_plant_generation` and `plot_arrows` are helper functions.
Tested against the notebooks that @victoriahunt used to generate figures for the Macro Grid report, the results are nearly identical (small differences in plot order, some line thicknesses, etc.). I figure that those small details can be ironed out in parallel with the main code review.
Using a CSV of demand center locations, we can reproduce the USA powerflow snapshots with e.g.:
```python
>>> from powersimdata.scenario.scenario import Scenario
>>> from postreise.plot.plot_powerflow_snapshot import plot_powerflow_snapshot
>>> import pandas as pd
>>> plot_powerflow_snapshot(Scenario(1270), '2016-11-02 22:00:00', …
```

feat: powerflow snapshot figure

---

postreise/analyze/generation/capacity_value.py
postreise/analyze/generation/tests/test_capacity_value.py
tox.ini

Continuation of https://github.com/Breakthrough-Energy/RenewableEnergyProject/issues/343
Adds the check to default `tox` invocation, as part of the `flake8` "testenv".
`tox -e flake8`
3 min

ci: add pep8-naming check to flake8

---

Dockerfile

Fix progress bar error when running notebook in container
Install [ipywidgets](https://ipywidgets.readthedocs.io/en/stable/user_install.html) to fix this [error](https://stackoverflow.com/questions/53247985/tqdm-4-28-1-in-jupyter-notebook-intprogress-not-found-please-update-jupyter-an)
I ran `!pip install ipywidgets` in the notebook and got a progress bar
30 sec

fix: install ipywidgets for tqdm progress bar

---

postreise/analyze/generation/costs.py
postreise/analyze/generation/emissions.py
postreise/analyze/generation/tests/test_costs.py

- Move cost calculation to its own module, since it may be used by people who aren't interested in emissions.
- Improve flexibility of cost calculation code.
The logic of cost calculation is not changed. We make it more flexible by taking either a Scenario or `pg` and `gencost` data frames (previous behavior). We correct the output so that it's actually a data frame (previously it was a numpy array, but the docstring said it was a data frame), and we make slight changes to the code in the `emissions` module so that it calls the new function in the right way, and appropriately uses the now-dataframe output.
The old method (passing pg and gencost) is still tested via the tests of the `emissions` module. The new method was tested manually.
5-10 minutes. This is fairly high priority to get …

refactor: move cost calculation function to separate module

---

setup.py

Copy data CSVs when package is installed via setup.py. This will allow the files to be accessed automatically, no matter how the package is installed, via code like:
```python
import inspect
import os
import postreise
postreise_data = os.path.join(os.path.dirname(inspect.getfile(postreise)), "data")
```
2 minutes.

chore: add data CSVs to package_data

---

requirements.txt

Cleanup from #243, removing `seaborn` package from requirements.txt that we don't actually require anymore.
5 seconds.

chore: remove seaborn from requirements

---

postreise/plot/colors.py
postreise/plot/plot_utilization_map.py

A couple of times now, we have needed to produce maps of all congested branches, with a custom color palette, and custom line thickness settings. This was achieved in a quick-and-dirty way by directly editing the hard-coded values in a local copy of PostREISE; this PR integrates these options into the plotting functions.
- We move the `traffic_palette` into **colors.py**
- We allow the user to supply a custom color palette.
- We change the hard-coded values for determining branch thickness into something user-configurable, with default values.
- We allow the user to specify the figure dimensions.
- We allow the user to specify whether the color bar is displayed or not.
- We make use of the built-in `plot_states` function, and allow the user to pass keyword arguments to this function to …

feat: improve flexibility of utilization, risk, and bind maps

---

postreise/analyze/transmission/upgrades.py
postreise/plot/plot_upgrades_map.py

Allow transmission upgrades plots to be created using any interconnection, and to properly plot new branches as well as scaled branches.
Closes #267.
In **upgrades.py**: we fix the merging of the two branch data frames to ensure that the lat/lon columns of the merged data frame include the lat/lon data of new branches.
In **plot_upgrades_map.py**:
- We make use of the `plot_states` function to simplify border plotting.
- Previously-hardcoded b2b_indices are now passed by the user.
- Previously-hardcoded figure sizes can now be passed by the user (default sizing remains, which is good for plotting USA).
- The user can specify explicit `x_range` and `y_range`, to be able to zoom into certain …

refactor: add flexibility to plot_upgrades_map

---

postreise/analyze/time.py
postreise/plot/plot_generation_ts_stack.py

Fix the bug described in #275 
Now it works as expected.
Note that we don't need to change the time zone if we slice a time series with timestamps in a different time zone.
5min

generation stack plot bug fix

---

.coveragerc
.github/workflows/test.yml
Pipfile
Pipfile.lock
pytest.ini
requirements.txt
tox.ini

Identical to Breakthrough-Energy/PowerSimData#471 except didn't add python 3.9 testing since pyproj is incompatible, so will address that separately

ci: add coverage report to pytest

---

postreise/analyze/transmission/upgrades.py
postreise/plot/plot_transmission_upgrades_map.py

Correct a bug where the `postreise.analyze.transmission.upgrades.get_dcline_differences` fails when comparing a grid with dclines connected to new buses. This also blocks the `postreise.plot.plot_transmission_upgrades_map.map_transmission_upgrades` function which relies on it.
```python
>>> from powersimdata import Scenario
>>> from bokeh.io import show
>>> from postreise.plot.plot_transmission_upgrades_map import map_transmission_upgrades
>>> show(map_transmission_upgrades(Scenario(2672), Scenario(3697)))
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "C:\Users\DanielOlsen\repos\bes\PostREISE\postreise\plot\plot_transmission_upgrades_map.py", line 293, in …
```

fix: correct bug where get_dcline_differences fails for DC lines connected to new buses

---

docs/code/capacity_vs_cf_solar_western_scatter.py
docs/code/capacity_vs_cost_curve_slope_coal_eastern_scatter.py
docs/code/capacity_vs_curtailment_solar_western_scatter.py
docs/code/capacity_vs_generation_bar.py
docs/code/capacity_vs_generation_pie.py
docs/code/curtailment_eastern.py
docs/code/curtailment_usa_heatmap.py
docs/code/emission_bar.py
docs/code/emission_map.py
docs/code/emission_map_carbon_diff.py
docs/code/energy_emission_stack_bar.py
docs/code/generation_stack_western_ts.py
docs/code/interconnection_map.py
docs/code/lmp_usa_map.py
docs/code/pf_snapshot_map.py
docs/code/shortfall_nv.py
docs/code/utilization_map.py
docs/plot.rst
tox.ini

It should help with simplifying the process to regenerate the plots. Not entirely sure what that looks like yet - ideally something fully automated but more likely just loading the files into a notebook. Either way, the code is more accessible since it's in `.py` files and broken up by plot.
Just moving things around, small fix to indentation, and running the formatting on the code.
Built the docs locally and compared result with the [plotting section](https://breakthrough-energy.github.io/docs/postreise/index.html#plotting-scenario-data) currently deployed.
10 min

refactor: move code snippets to files

---

postreise/plot/plot_transmission_upgrades_map.py

- Change hard-coded values to user-facing parameters with default values.
- Separate the init of a bokeh figure from the addition of upgrades information.
- Add a parameter to filter display of DC line additions by length
- Add parameter to control legend display
The only effective code change is allowing the user to filter the display of DC lines by minimum length, and to allow the user to size and locate the legend. All other changes are just reorganization of the code.
Tested manually, still works.
15 minutes.

refactor: improve the flexibility of the transmission upgrades map

---

docs/README.md
docs/docker-compose.yml
docs/helper.py
docs/run_snippets.ipynb

The plots used on the docs website require specific scenarios as well as an environment to run the code snippets. The goal here is to simplify that as much as possible, so we can recreate the content as needed, e.g. to take advantage of new functionality.
What's involved:
* zip file with scenario data uploaded to blob storage
* docker-compose file for self contained environment
* notebook which generates the code used to run/save each code snippet
I ran the notebook and compared the results with currently checked in files. There are a few minor differences, but that is due to inconsistencies in the code snippets, which we can fix separately if needed. 
If github will render the notebook, that is probably the most useful place to look
20 min

Simplify process to generate plotting documentation

---

.github/workflows/coverage.yml
README.md

I failed at copy/paste - we need to checkout PowerSimData for the tests to work. This time I ran the workflow so that codecov registered PostREISE and created the badge. 
You can see the report generated by this branch [here](https://codecov.io/gh/Breakthrough-Energy/PostREISE/commit/42dd531d084aab3a2bd491e2e495d4c4700ad25b/). Once it works on develop, the badge link will show results. 
3 min

chore: fix yaml and add badge

---

README.md

Add a sentence in the README that states that **PowerSimData** must be cloned next to **PostREISE**. It tricked me yesterday.
No code
N/A
The **Depencies** section
N/A
2min

docs: clarify PowerSimData dependency

---

postreise/analyze/tests/__init__.py
postreise/analyze/transmission/upgrades.py
postreise/plot/plot_capacity_map.py
postreise/plot/plot_carbon_map.py
postreise/plot/plot_curtailment_ts.py
postreise/plot/plot_generation_ts_stack.py
postreise/plot/plot_heatmap.py
postreise/plot/plot_interconnection_map.py
postreise/plot/plot_lmp_map.py
postreise/plot/plot_powerflow_snapshot.py
postreise/plot/plot_scatter_capacity_vs_capacity_factor.py
postreise/plot/plot_scatter_capacity_vs_cost_curve_slope.py
postreise/plot/plot_scatter_capacity_vs_curtailment.py
postreise/plot/plot_transmission_upgrades_map.py

Sphinx uncovers some bad imports following #310. This PR fixes the import statements. It also anticipates the renaming of the function in Breakthrough-Energy/PowerSimData#518. Finally, I cleaned up an \_\_init\_\_ file
* Modify import statements of functions that are not tested
Sphinx is able to import all modules
Import statements
N/A
5min

Fix import statements

---

.coveragerc

We forgot to update the config here, so coverage is appearing lower than it should (at least relative to the other repos).
Stop excluding test files in the measurement.
n/a
1 min

fix: remove filter on coverage measurement

---

.github/workflows/test.yml
Pipfile
Pipfile.lock
postreise/analyze/transmission/tests/test_congestion_surplus.py
requirements.txt
setup.cfg

- Prepare for a v0.5.1 release of PostREISE
- Update requirements of dependency versions: Pandas, PowerSimData, PyProj. Remove `seaborn` from `Pipfile` (cleanup from #272)
- Update list of supported/tested python versions (was 3.7 and 3.8, now 3.8, 3.9, 3.10)
Besides updating version numbers, we temporarily disable the tests of the calculation of congestion surplus, since these depend on a part of the PowerSimData API that changed between v0.4.5 and v0.5.0. These will be re-enabled in #328.
Unit tests pass for Python 3.8, 3.9, and 3.10.
5 minutes.

chore: bump versions of PostREISE, Python, and dependencies

---

postreise/analyze/transmission/congestion.py
postreise/analyze/transmission/tests/test_congestion_surplus.py

Get `bus_demand` via the `Scenario.get_bus_demand()` method instead of importing the `get_bus_demand` function, which is being removed in https://github.com/Breakthrough-Energy/PowerSimData/pull/581. Closes https://github.com/Breakthrough-Energy/PostREISE/issues/327.
Tested manually. With the PowerSimData branch for the PR installed:
```python
>>> from powersimdata import Scenario
>>> from postreise.analyze.transmission.congestion import calculate_congestion_surplus
>>> calculate_congestion_surplus(Scenario(3873))
UTC
2016-10-01 00:00:00    272789.533136
2016-10-01 01:00:00    272558.733281
2016-10-01 02:00:00    252855.877419
2016-10-01 03:00:00    248522.565691
2016-10-01 04:00:00 …
```

refactor: get bus_demand via Scenario method instead of import

---

.coveragerc
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/workflows/coverage.yml
.github/workflows/packages.yml
.github/workflows/test.yml
Pipfile
Pipfile.lock
README.md
postreise/analyze/transmission/congestion.py
postreise/analyze/transmission/tests/test_congestion_surplus.py
postreise/plot/plot_carbon_map.py
requirements.txt
setup.cfg

Merge develop into master for v0.5.1 release.
- Refactor maps (#304)
None
- ci: remove unnecessary clone step (#319) (@jon-hagg)
- fix: remove filter on coverage measurement (#320) (@jon-hagg)
- docs: improve section on documentation in README (#324) (@rouille)
- docs: change author (#325) (@rouille)
- Update assignees for issue templates (#326) (@kasparm)
- refactor: get bus_demand via Scenario method instead of import (#328) (@danielolsen)
- style: update code style to latest black version (#329) (@danielolsen)
- chore: bump versions of PostREISE, Python, and dependencies (#330) (@danielolsen)
**Full Changelog**: https://github.com/Breakthrough-Energy/PostREISE/compare/v0.5.0...v0.5.1
5 …

chore: merge develop into master for v0.5.1 release

---

postreise/analyze/demand.py
postreise/analyze/generation/curtailment.py
postreise/analyze/generation/summarize.py
tox.ini

Clean up ***tox.ini*** file and fix warnings raised by the test suite
Convert `set` to `list` when using indexer in data frame to fix `pandas`' `FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead`
Run `tox` successfully
Remaining warnings come from `owersimdata/input/helpers.py` (l. 277) that has been fixed in https://github.com/Breakthrough-Energy/PowerSimData/pull/609 and will propagate in **PostREISE** the next time we release **PowerSimData**
* Remove unnecessary environment variables in ***tox.ini*** file
* Several modules where data frame are queried using `set`
N/A
2 min

Clean up tox file and fix warnings

---

postreise/analyze/transmission/upgrades.py

Remove obsolete module
N/A
Run `tox` successfully
The `calculate_branch_difference` and `calculate_dcline_difference` functions have been moved into `powersimdata.design.compare.transmission`. The `postreise.analyze.transmission.upgrades` module is never imported in **PostREISE**
N/A
2 min

Remove obsolete module

---

.github/workflows/release.yml

Automatically build and push the `postreise:stable` image when we release a new package to PyPI. 
Add the step to the workflow to trigger the docker build workflow in plug. 
Tested the workflow in my test-ci repo. What I'm not totally sure of is if there is a delay, cache, etc somewhere that could cause the docker build to still pick up the old package. We'll see when we run this, and worst case will have to run the workflow again manually.
For reference, the workflow id comes from the api: https://api.github.com/repos/Breakthrough-Energy/plug/actions/workflows
5 min

ci: trigger stable image build

---

postreise/plot/plot_sim_vs_hist.py
postreise/plot/tests/test_plot_sim_vs_hist.py

Refactor the `plot_generation_sim_vs_hist` function to remove its dependency on a `ScenarioInfo` object
* Use a `Scenario` object in place of a `ScenarioInfo` object
* Check type and value of the parameters
* Write tests for the function
New tests
In the `postreise.plot.plot_sim_vs_hist` module and the corresponding tests
N/A
15min

Remove dependency on ScenarioInfo objects

---

Pipfile
Pipfile.lock
postreise/analyze/generation/curtailment.py
postreise/analyze/generation/summarize.py
postreise/plot/plot_bar_generation_max_min_actual.py
postreise/plot/plot_bar_generation_stack.py
postreise/plot/plot_bar_generation_vs_capacity.py
postreise/plot/plot_bar_renewable_max_profile_actual.py
postreise/plot/plot_curtailment_ts.py
postreise/plot/plot_scatter_capacity_vs_curtailment.py
postreise/plot/tests/test_plot_bar_generation_max_min_actual.py
postreise/plot/tests/test_plot_bar_renewable_max_profile_actual.py

Update PowerSimData version and fix subsequent error raised
Propagate changes made  to check functions of PowerSimData following refactor to make them independent of grid models. Some warnings raised when running the tests were fixed.
Existing unit tests
Several analysis and plot modules were affected.
N/A
10min

Update PowerSimData version

---

.github/workflows/release.yml

We should trigger a docker build of the `postreise:stable` image when we publish a new release to PyPI. However, this will not work if the input argument is not spelled correctly. The workflow doesn't explicitly fail, but it does emit the following [error message](https://github.com/Breakthrough-Energy/PostREISE/runs/7906863422?check_suite_focus=true#step:9:29). 
Change the argument name to match the workflow being run - see https://github.com/Breakthrough-Energy/plug/blob/main/.github/workflows/docker-build.yml#L6
I believe this was tested when I added the parameterization here https://github.com/Breakthrough-Energy/actions/pull/8, but that didn't stop typos from occurring. Not sure how to test unless we do another release, but we can run the docker build workflow manually, so it's not …

Fix typo in argument to workflow trigger

---

postreise/analyze/generation/summarize.py
postreise/analyze/generation/tests/test_summarize.py

Add note and print statement in the `sum_generation_by_type_zone` function. Closes issue #339.
Add a print statement if a condition is not met on parameter setting.
New unit test
* new `if` statement in function
* new test checking that the print statement is well triggered
N/A
5min

Add note and print statement to describe function's behavior

---

docs/README.md
docs/docker-compose.yml
docs/helper.py

After the latest release of powersimdata and postreise, any scenario can be loaded from blob storage, so there is no need to download a separate zip file in order to create the plots used in the tutorial. As such we can simplify the readme for this process.
Update the readme, fix an issue saving the base64 encoded image data (not sure if this is due to a jupyter/ipython update to how outputs are handled, but didn't care enough to find out), and rerun the notebook to ensure it works. I also removed the pf snapshot from the output, which reduces the notebook size from 17MB to 20KB. 
Regenerated the plots and did some spot checks between `docs/img` (currently in git) and `docs/img2` (where new outputs are written). So far I've only seen minor differences in the formatting, e.g. different …

Update plotting documentation

---

docs/code/curtailment_eastern.py

Switch the order of plots to match the configuration [here](https://github.com/Breakthrough-Energy/PostREISE/blob/develop/docs/helper.py#L6) which is used to generate the notebook cell, then subsequently save the plots. I noticed while comparing the recently generated plots that the `curtailment_solar_eastern_ts.png` was actually for wind, and vice versa. This was slightly simpler than fixing helper.py and the notebook.
See above.
Ran the notebook and compared plots. Checked the `plot.rst` to make sure there is no dependence on the order (it just includes the two images)
30 sec

docs: switch order of plots to match notebook

---

postreise/plot/plot_scatter_capacity_vs_cost_curve_slope.py
postreise/plot/tests/test_plot_scatter_capacity_vs_cost_curve_slope.py

Test the `plot_scatter_capacity_vs_cost_curve_slope` plotting function. Closes #355.
Add checks on parameter and write unit tests
New unit tests.
* Add a new test module
* Change the `show_plot` parameter to `plot_show` as this is what is used in a majority of module. In fact we have both version but a little more of `plot_show`
N/A
5min

Write tests for plotting function plot_scatter_capacity_vs_cost_curve_slope

---

postreise/plot/plot_scatter_capacity_vs_curtailment.py
postreise/plot/tests/test_plot_scatter_capacity_vs_curtailment.py

Test the `plot_scatter_capacity_vs_curtailment` plotting function. Closes #3557
Add checks on parameter and write unit tests
New unit tests.
* Add a new test module
* Change the `show_plot` parameter to `plot_show` as this is what is used in a majority of module. In fact we have both version but a little more of `plot_show`
N/A
5min

Write tests for plotting function plot_scatter_capacity_vs_curtailment

---

postreise/plot/plot_pie_generation_vs_capacity.py
postreise/plot/tests/test_plot_pie_generation_vs_capacity.py

Test the `plot_pie_generation_vs_capacity` plotting function. Closes #359.
* Use `list` instead of `set` as indexer of data frame to avoid a warning;
* Instantiate the `ModelImmutables` class with `interconnect` to only access the geographical mappings for the interconnect(s) of the scenario;
* Write unit tests.
* Write new unit tests;
* Run demo notebook.
* Add a new test module
* Change instantiation of `ModelImmutables`
* Change type of indexer in data frame
N/A
5min

Write tests for plotting function plot_pie_generation_vs_capacity

---

postreise/plot/plot_bar_shortfall.py
postreise/plot/tests/test_plot_bar_shortfall.py

Improve test coverage of the `plot_bar_shortfall` function. The docstring of the function is formatted. Closes #361.
N/A
Add new tests to hit missing statements. More specifically, the function is called with new sets of the `areas` parameter. 
Before:
```
Name                                                                     Stmts   Miss Branch BrPart  Cover
----------------------------------------------------------------------------------------------------------
postreise/plot/plot_bar_shortfall.py                                        89     16     48      9    80%
```
After:
```
Name                                                                     Stmts   Miss Branch BrPart  Cover …
```

Improve test coverage for plotting function plot_bar_shortfall

---

postreise/analyze/generation/emissions.py
postreise/analyze/generation/tests/test_emissions.py
postreise/plot/plot_carbon_bar.py

Move analysis function `carbon_diff` from `postreise.plot.plot_carbon_bar` to `postreise.analyze.generation.emissions` and write tests. Closes #366.
N/A
New unit test
* Function is added to `postreise.analyze.generation.emissions` module and deleted from `postreise.plot.plot_carbon_bar`
* Write a unit test in the `postreise.analyze.generation.tests.test_emissions` module
N/A
2min

Relocate function

---

postreise/plot/plot_carbon_bar.py
postreise/plot/tests/test_plot_carbon_bar.py

Write test for plot_carbon_bar plotting function. Closes #370.
Add a check to ensure that scenarios are in analyze state and use `plot_show` parameter across the entire function (a `if` statement was on `show_plot`) 
New unit tests
New test module and small changes in plotting function
N/A
5min

Write test for plotting function plot_carbon_bar

---

postreise/plot/tests/test_plot_capacity_map.py

Write test for `map_plant_capacity` plotting function. Closes #372 
Test the function
New tests
A new `postreise.plot.tests.test_plot_capacity_map` module has been created
N/A
5min

Write test for plotting function map_plant_capacity

---

postreise/plot/plot_scatter_capacity_vs_curtailment.py
postreise/plot/tests/conftest.py
postreise/plot/tests/test_plot_capacity_map.py
pytest.ini
tox.ini

Fix warnings. There are three kinds of warnings
* one raised by `pandas` regarding the type of array used for indexing a data frame
* one raised by `bokeh` because we attempt to edit an empty legend
* one raised by `matplotlib` because too many figures have been opened
Closes #374.
* Use a `list` in place of a `set` to  index data frame in `plot_scatter_capacity_vs_curtailment`
* Use only coal generator to ensure glyphs are rendered on the map and legend is created in `test_plot_capacity_map`
* Close all plots in each test module where plots are generated
Warnings are not raised
Changes are mostly done in the test modules
N/A
5min

Fix warnings raised by tests

---

Pipfile.lock

Regenerate **Pipefile.lock**. The `cryptography` package is updated to 38.0.3, which is no longer vulnerable to security issues (see [alerts](https://github.com/Breakthrough-Energy/PostREISE/security/dependabot))'
Other packages are also updated but all unit tests pass.
N/A
Existing unit tests
Dependencies have been updated in **Pipefile.lock**
N/A
2min

Regenerate pipenv lockfile
