- README.md
Provide a link for user to install the whole model as well as the contribution guide.
README first paragraph
5min
> docs: add link to installation and contribution guide

- .github/workflows/docs-trigger.yml
Copy paste from Breakthrough-Energy/PowerSimData#402
> ci: use custom action to trigger docs build

- postreise/plot/plot_bar_generation_vs_capacity.py
Fix link to function in docstring. `plot` was missing in the path. Since the function is declared in the same module there is no need to use the full path.
30s
> docs: fix link to function in docstring

- postreise/plot/plot_bar_generation_vs_capacity.py
- postreise/plot/plot_heatmap.py
A couple more docstrings that were incorrectly referencing a function are corrected.
1 min
> docs: fix link to function in docsting

- .github/ISSUE_TEMPLATE/bug_report.md
Same as https://github.com/Breakthrough-Energy/PowerSimData/pull/454
> chore: create bug report issue template

- README.md
Add logo and badges to README, Addresses Breakthrough-Energy/RenewableEnergyProject#342
N/A
N/A
Top of README where the BES logo and the:
* Made with Python
* Code of conduct
* Contributors
* Commit activity
* Last commit
* Pull Requests open
are imported
The README can be seen [here](https://github.com/Breakthrough-Energy/PostREISE/blob/ben/badge/README.md)
2min.
> Add logo and badges to README

- .github/workflows/coverage.yml
- .github/workflows/packages.yml
- tox.ini
Same as what we did in PowerSimData - output the report as xml and upload to codecov.io. 
Added the workflow and parameterized the tox command. Also, added the dependencies label to PRs created automatically for package updates.
n/a
Will add the badge once this repo is synced with codecov - that will link to the report
3 min
> Upload coverage report

- setup.cfg
> chore: bump version number to v0.5.0

- README.md
Update README to reflect package availability on PyPi
No code, just installation option instructions (and a new badge!), essentially copy-pasted from https://github.com/Breakthrough-Energy/PowerSimData/pull/536.
2 minutes
> doc: update README to signal package availability on PyPi

- .github/workflows/coverage.yml
- .github/workflows/packages.yml
- .github/workflows/test.yml
Additional simplifications we can make as a result of installing powersimdata from PyPI. 
Remove extra clone from workflows.
n/a
Related PR https://github.com/Breakthrough-Energy/PreREISE/pull/215. 
5 min
> ci: remove unnecessary clone step

- README.md
Add links to docstrings and package overview in README. 
N/A
N/A
In the **Documentation** section of the README
You can take a look [here](https://github.com/Breakthrough-Energy/PostREISE/blob/ben/readme/README.md).
2min
> docs: improve section on documentation in README

- setup.cfg
Change author and author email for the package
N/A
N/A
Author is now Breakthrough Energy in **setup.cfg**
N/A
2min
> docs: change author

- postreise/plot/plot_carbon_map.py
Update code style to latest black version, so that automated checks pass.
1 minute.
> style: update code style to latest black version

- docs/index.rst
- docs/scenario.rst
Describe scenarios used in tutorial
N/A
Run `tox` in the **docs** and checked in my browser that the new section is correctly displayed
* A new reStructuredText file enclosing the section describing the scenarios used in the tutorial is created 
* A link to the above file is created in the index
5min
> Describe scenarios used in tutorial

- requirements.txt
- setup.cfg
> chore: bump version to 0.5.2

- postreise/plot/plot_tornado.py
- postreise/plot/tests/test_plot_tornado.py
Test the `plot_tornado` plotting function. Closes #363.
Add checks on parameter and write unit tests
New unit tests.
* Add a new test module
* Raise error on parameters
N/A
5min
> Write tests for plotting function plot_tornado

- .github/workflows/coverage.yml
- .github/workflows/lint.yml
- .github/workflows/packages.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
Update the version of `checkout` and `setup-python`. 
CI
5.2 sec
> ci: update action versions

- postreise/plot/plot_bar_generation_max_min_actual.py
- postreise/plot/plot_bar_renewable_max_profile_actual.py
Fix docstrings generating some warnings when generating the docs
N/A
N/A
Missing the closing backticks
N/A
5s
> Fix docstrings

- docs/analyze.rst
Remove extra indentation in one of the code snippet of the [tutorial]()
N/A
N/A
indentation in code snippet
Before:
After:
30s
> Fix indent in code snippet

- setup.cfg
> chore: bump version to 0.5.3
